---
# handlers file for roles/myrole
- name: jinja-to-index
  ansible.builtin.template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html

- name: jinja-to-index
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
    enabled: true
